services:
  course:
    build: microservices/course-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network
    #depends_on:
     # postgres:
      #  condition: service_healthy

  review:
    build: microservices/review-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network
    #depends_on:
     # mongodb:
      #  condition: service_healthy

  course-composite:
    build: microservices/course-composite-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network