server.port: 8888

spring.cloud.config.server.native.search-locations: file:${PWD}/config-repo

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
---
spring.config.activate.on-profile: docker,native
spring.cloud.config.server.native.search-locations: file:/config-repo