app:
  jwk-set-uri: ${APP_KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/course-management-realm/protocol/openid-connect/certs}
server:
  port: 9001
spring:
  application:
    name: course-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: pwd
    url: jdbc:postgresql://localhost:5432/course_db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5 #https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
 # flyway: # Only in dev env. Never have them in prod
 #   validate-on-migrate: false
 #   outOfOrder: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/course-management-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/course-management-realm/protocol/openid-connect/certs}
logging:
  level:
    org.springframework: INFO
    com.javatab: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
app:
  jwk-set-uri: http://keycloak:8080/realms/course-management-realm/protocol/openid-connect/certs
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/course_db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/course-management-realm
          jwk-set-uri: http://keycloak:8080/realms/course-management-realm/protocol/openid-connect/certs
server:
  port: 8080