apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yml: |
    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks

    usage_report:
      reporting_enabled: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 1000  # Ensures write permission to the storage path
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - "-config.file=/etc/tempo-config.yml"
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 3200
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo-config.yml
              subPath: tempo.yml
            - name: tempo-storage
              mountPath: /tmp/tempo/blocks
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: tempo-http
      protocol: TCP
      port: 3200
      targetPort: 3200
  type: ClusterIP
