apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo-config.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            http:
            grpc:
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo
    compactor:
      compaction:
        block_retention: 24h

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - "-config.file=/etc/tempo/tempo-config.yaml"
          ports:
            - containerPort: 3200
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
