server:
  port: 9002
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/review-db
      #host: localhost
      #port: 27017
      #database: review-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/course-management-realm
          jwk-set-uri: http://localhost:8081/realms/course-management-realm/protocol/openid-connect/certs
logging:
  level:
    org.springframework: INFO
    com.javatab: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongodb:27017/review-db
server:
  port: 8080