apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-mongodb
  labels:
    app: review-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-mongodb
  template:
    metadata:
      labels:
        app: review-mongodb
    spec:
      containers:
        - name: review-mongodb
          image: mongo:6.0.4  # Latest stable MongoDB version
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          emptyDir: {}  # Use PersistentVolumeClaim for production