apiVersion: v1
kind: Service
metadata:
  name: review-mongodb
spec:
  selector:
    app: review-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
