global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'course-composite-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
         - 'course-composite:8080'
         - 'course:8080'
         - 'review:8080'
         - 'gateway-service:9000'