app:
  course-service:
    host: localhost
    port: 9001
  review-service:
    host: localhost
    port: 9002
spring:
  application:
    name: course-composite-service
server:
  port: 5000
logging:
  level:
    root: INFO
    io.javatab.microservices.composite.course: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080
app:
  course-service:
    host: course
    port: 8080
  review-service:
    host: review
    port: 8080